version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.17
    - 7.13.16
  - dependency-name: postcss
    versions:
    - 8.2.4
    - 8.2.5
    - 8.2.9
  - dependency-name: cypress
    versions:
    - 6.7.0
    - 6.7.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
